name: explorer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 6.7.2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  path: ^1.8.2
  sqflite: ^2.2.0+3
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  intl: ^0.17.0
  disk_space: ^0.2.1
  path_provider: ^2.0.11
  image: ^3.2.2
  open_file: ^3.2.1
  uuid: ^3.0.6
  share_plus: ^4.5.3
  flutter_animator: ^3.2.2
  video_player: ^2.4.8
  change_app_package_name: ^1.1.0
  shimmer: ^2.0.0
  volume_controller: ^2.0.6
  qr_code_scanner: ^1.0.1
  dio: ^4.0.6
  qr_flutter: ^4.0.0
  device_info_plus: ^4.0.0
  draggable_scrollbar: ^0.1.0
  connectivity_plus: ^3.0.2
  mime: ^1.0.4
  just_audio: ^0.9.31
  web_socket_channel: ^2.3.0
  logger: ^1.1.0
  lottie: ^2.2.0
  wakelock: ^0.6.2
  font_awesome_flutter: ^10.3.0
  async: ^2.10.0
  image_picker: ^0.8.6+1
  flutter_image_compress: ^1.1.3
  url_launcher: ^6.1.9
  introduction_screen: ^3.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bitsdojo_window: ^0.1.2
  clipboard: ^0.1.3
  firebase_crashlytics: ^3.0.14
  firebase_core: ^2.6.1
  firebase_analytics: ^10.1.3
  firebase_performance: ^0.9.0+13
  file_picker: ^4.6.1
  awesome_notifications: ^0.7.4+1
  external_path: ^1.0.3
  move_to_background: ^1.0.2
  flutter_foreground_service: ^0.3.0
  audio_service: ^0.18.9
  localization: ^2.1.0
  rxdart: ^0.27.7
  dart_vlc: ^0.3.0
  window_manager: ^0.2.9
  firedart: ^0.9.0+1
  desktop_drop: ^0.4.1
  ffi: ^1.2.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/whatsapp/
    - assets/ext_icons/icons_1/
    - assets/icons/recent/
    - assets/anim/
    - assets/icons/intro/
    - assets/languages/
 
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_wght.ttf
